### ISSUE TITLE
Doesn't Work

### ISSUE THREAD

**Issue by ty-meador** [Hamza-Aziane/obsidian-dark#4]
I just installed this, it's my favorite theme on all my editors. But When I try it with codeoss it doesn't stick. I'm not sure why, but when I click "use theme" it takes, but when I switch back to my code editor it switches right back. Any ideas? The included themes are aweful. This one is the only one I've ever liked;

**Comment by aziham** [comment]
Hi @ty-meador. It's great to hear that you enjoy using my theme, and I appreciate you taking the time to provide feedback.

I'm sorry to hear that you're experiencing issues with Codeoss, and I want to let you know that I have only tested the theme on VSCodium and VSCode.

Unfortunately, I'm unable to dedicate time to improving it further at the moment due to other commitments.

That being said, I plan to rename the theme and make it available for use on different editors in the future.
Rest assured that I will address this issue once I make those changes.

Thank you for your understanding and patience.
